bot:
  website: https://www.example.com
  token: 5856609274:AAFn7XeOaaGuKc-VmYQo3ywPQ5X2eF9esNk
  admin_id: 
   - 5611253292
   - 5868721737
  group_id: -885377620
apps:
  database:
    ip: 1.117.223.151
    port: 3306
    user: aiko
    pass: CanCwNfHE2GkMPkb
    name: aiko	
  # proxy: http://amiss:921920@54.175.181.68:12345